# Generated by Django 4.0.4 on 2022-05-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcode',
            name='filepath',
        ),
        migrations.AddField(
            model_name='projectcode',
            name='code',
            field=models.CharField(default='', max_length=8192),
        ),
    ]
